kafka_user: "{{ lookup('env','USER') }}"
kafka_version: 2.8.1
scala_version: 2.13
kafka_download_url: https://archive.apache.org/dist/kafka/{{ kafka_version }}/kafka_{{ scala_version }}-{{ kafka_version }}.tgz
kafka_download_dest: /home/{{ kafka_user }}/tmp
kafka_install_dest: /home/{{ kafka_user}}/tools
kafka_plugin_path: /home/{{ kafka_user}}/tools/camel-kafka-connectors


