{
 "title": "Camel Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(org_apache_camel_camel_1_UptimeMillis, job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(org_apache_camel_camel_1_UptimeMillis{job=\"$job\"}, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Global Event Rate: Routes",
   "type": "timeseries",
   "description": "Total number of exchanges per route",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "events" } },
   "targets": [
    {
     "expr": "rate(org_apache_camel_camel_1_ExchangesTotal{job=\"$job\", type=\"routes\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Global Event Rate: Processors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "events" } },
   "targets": [
    {
     "expr": "rate(org_apache_camel_camel_1_ExchangesTotal{job=\"$job\", type=\"processors\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Global Event Rate: context",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "events" } },
   "targets": [
    {
     "expr": "rate(org_apache_camel_camel_1_ExchangesTotal{job=\"$job\", type=\"context\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Exchanges Completed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "events" } },
   "targets": [
    {
     "expr": "rate(org_apache_camel_camel_1_ExchangesCompleted{job=\"$job\", type=\"routes\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Route Policy Seconds Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "CamelRoutePolicy_seconds_max", "legendFormat": "{{routeId}}" }
   ]
  }
 ]
}